helius-labs/helius-rust-sdk

src/webhook.rs
This PR adds the ability to remove addresses from a given webhook via the new `remove_addresses_from_webhook` method
=> feat(webhook): Add `remove_addresses_from_webhook`

README.md
This PR adds `remove_addresses_from_webhook` to the `README.md` and organizes the webhook methods alphabetically
=> feat(docs): Add `remove_addresses_from_webhook` to `README`

examples/get_parsed_transaction_history.rs, src/enhanced_transactions.rs, src/types/enhanced_transaction_types.rs
Added ability paginate the results of the request in the transaction history, by doing the following:
1. Creating a new request type called ParseTransactionHistoryRequest that has an `address` String and an Option `before` String
2. Updated `parsed_transaction_history` to input the new type, and update the API call if `before` exists. Updated documentation above it.
3. Updated the example to reflect the change
I've never contributed to an open-source project, so please forgive me if this is the wrong process for suggesting edits or updates to the module. 
I looked through the code to adhere to similar structures that y'all used in other aspects, but either way this should be a complete fix here or a good start to this implementation.
Any feedback or comments please let me know. Otherwise …
=> feat(parsed_transaction_history): add transaction pagination

examples/get_priority_fee_estimate.rs, src/types/enums.rs, src/types/types.rs, tests/rpc/test_get_priority_fee_estimate.rs
This PR aims to add a few fixes to the `priority_fee_estimate` method by changing the `None` enum type for `PriorityLevel` to `Min` and introduces the new `recommended` option
=> fix(priority_fee_estimate): Change `None` to `Min` and Add `recommended` Option

src/request_handler.rs
This PR directly addresses and rectifies the issue raised in #25 regarding how empty response bodies are handled
=> fix(request_handler) Handle Empty Response Body

Cargo.toml, examples/get_priority_fee_estimate.rs, src/error.rs, src/lib.rs, src/optimized_transaction.rs, src/types/types.rs, tests/rpc/test_get_priority_fee_estimate.rs
This PR aims to add a `send_smart_transaction` method, which builds and sends an optimized transaction. It also adds the `get_compute_units` and `poll_transaction_confirmation` methods and new error types. Finally, it adds the new `include_vote` parameter to `GetPriorityFeeEstimateOptions`
=> feat(optimized_transactions): Add `send_smart_transaction` Functionality

src/types/options.rs, src/types/types.rs, tests/rpc/test_get_asset.rs, tests/rpc/test_get_asset_batch.rs, tests/rpc/test_get_assets_by_authority.rs, tests/rpc/test_get_assets_by_creator.rs, tests/rpc/test_get_assets_by_group.rs, tests/rpc/test_get_assets_by_owner.rs, tests/rpc/test_search_assets.rs
This PR aims to surface the `show_native_balance` option for search asset calls, as well as fix a `SerdeJson` error that would be thrown if an asset's name and symbol are not specified in the `Metadata`
=> fix(search_assets): Surface `show_native_balance` and Fix `SerdeJson` Error 

examples/append_address_to_webhook.rs, examples/create_webhook.rs, examples/delete_webhook.rs, examples/edit_webhook.rs, examples/get_all_webhooks.rs, examples/get_webhook_by_id.rs, examples/remove_address_from_webhook.rs
This pull request adds examples of webhook functions to the project. The new examples demonstrate how to implement and use webhooks effectively, providing clear and practical usage scenarios.
These additions aim to help developers understand and implement webhook functionality more easily.
=> feat(webhook): Add Webhook Examples

README.md, examples/get_latest_blockhash_async.rs, src/client.rs, src/error.rs, src/factory.rs, tests/rpc/test_get_asset.rs, tests/rpc/test_get_asset_batch.rs, tests/rpc/test_get_asset_proof.rs, tests/rpc/test_get_asset_proof_batch.rs, tests/rpc/test_get_assets_by_authority.rs, tests/rpc/test_get_assets_by_creator.rs, tests/rpc/test_get_assets_by_group.rs, tests/rpc/test_get_assets_by_owner.rs, tests/rpc/test_get_nft_editions.rs, tests/rpc/test_get_priority_fee_estimate.rs, tests/rpc/test_get_rwa_asset.rs, tests/rpc/test_get_signatures_for_asset.rs, tests/rpc/test_get_token_accounts.rs, tests/rpc/test_search_assets.rs, tests/test_client.rs, tests/test_enhanced_transactions.rs, tests/test_mint_api.rs, tests/webhook/test_append_addresses_to_webhook.rs, tests/webhook/test_create_webhook.rs, tests/webhook/test_delete_webhook.rs, tests/webhook/test_edit_webhook.rs, tests/webhook/test_get_all_webhooks.rs, tests/webhook/test_get_webhook_by_id.rs, tests/webhook/test_remove_addresses_from_webhook.rs
This PR addresses the fact that the current embedded Solana client is synchronous, while the rest of the SDK is meant for asynchronous use. To avoid breaking changes, a `new_with_async_solana` method was added to the `Helius` client so users can generate an async Solana client.
In the future, we should consider making the SDK default to an asynchronous embedded Solana client. However, this is sufficient for now
=> feat(client): Add an Async Solana Client

src/optimized_transaction.rs, src/types/types.rs
This PR aims to allow multiple signers for the `send_smart_transaction` method. It also updates `get_compute_units` to account for this change
=> feat(optimized_transactions): Allow Multiple Signers For `send_smart_transaction`

src/optimized_transaction.rs, src/types/enums.rs
This PR aims to separate the smart transaction creation process in `send_smart_transaction` and provide it as a separate function `create_smart_transaction`
=> feat(optimized_transaction): Separate Smart Transaction Creation

src/optimized_transaction.rs
This PR aims to address the fact that the `send_smart_transaction` method returns early before retrying after initially polling the transaction's confirmation status
=> fix(optimized_transaction): Fix Retry Logic For `send_smart_transaction`

src/optimized_transaction.rs, src/types/types.rs
The goal of this PR is twofold:
- Fix the spelling for `TransferFeeConfig`'s `new_transfer_fee` field
- Formatting
=> fix(types): `TransferFeeConfig` + Formatting

src/optimized_transaction.rs, src/types/types.rs
This PR addresses the issue where a transaction fails during signature verification when using a different fee payer account. I've also created a separate `CreateSmartTransactionConfig` so we don't pass in send options for the transaction creation unnecessarily. `SmartTransactionConfig` has also been reworked to reflect this change
This is a port of [this PR from the Helius Node.js SDK](https://github.com/helius-labs/helius-sdk/pull/100)
=> fix(optimized_transaction): Address Issue When Using Different Fee Payer Account

.github/workflows/rust.yml
This PR aims to address the issue recently where checks have been failing because we run out of disk space on the GitHub Actions runner. This PR modifies the workflow to include cleanup steps and use artifacts so we don't have to constantly rebuild from scratch
=> fix(workflows): Clean Up Disk Space and Use Artifacts

Cargo.toml, src/jito.rs, src/lib.rs, src/types/types.rs
This PR aims to implement the first version of Jito Smart Transactions, as well as add a whole host of Jito functionality to the SDK. For the first iteration, we allow users to create a single, optimized transaction that pays a Jito tip with the method `create_smart_transaction_with_tip`. We also provide creating, sending, and polling functionality for a single, optimized transaction with a Jito tip via `send_smart_transaction_with_tip`
This is a 1-to-1 port of [this PR in the Helius Node.js SDK](https://github.com/helius-labs/helius-sdk/pull/101) and will provide the exact same functionality
=> feat(jito): Implement Jito Smart Transactions

src/request_handler.rs, tests/test_request_handler.rs
Getting the error message description text from a 400 response is not working. I'm seeing `Unknown error` returned every time it fails for me.
While I haven't actually tested this. I'm pretty sure it should be getting the `error` value here not `message`, refer screen shot:
another example 400 response:
`"{"error":"reached webhook limit"}"`
So this error format above seems to only be returned by the post webhook api.
For other apis errors are returned in this format:
```
{
"jsonrpc": "2.0",
"error": {
"code": -32603,
"message": "internal error: please contact Helius support if this persists"
}
}
```
Which is where I think getting `message` came from (still incorrect though as it would need to be accessed by `error.message`)
=> fix(request_handler) to read error message from error json body

src/types/types.rs
=> fix(types): mismatch

src/optimized_transaction.rs
This PR aims to address #58 by allowing the user to skip signature verification for `get_compute_units` if no signers are provided. This is achieved by making `signers` optional and setting `sig_verify` to `signers.is_some()`
=> feat(optimized_transaction): Better `get_compute_units`

README.md, src/optimized_transaction.rs, src/types/types.rs
This PR aims to add `send_smart_transaction_with_seeds`, which sends a smart transaction using seed bytes. This method would allow for sending smart transactions in async contexts where the `Signer` trait's lack of `Send + Sync` would otherwise cause issues (i.e., the issue outlined in #61)
=> feat(optimized_transaction): Implement `send_smart_transaction_with_seeds`

.github/workflows/rust.yml
This PR aims to update the build artifacts in the workflow file to v4, to resolve issues where the runner would fail as v2 is deprecated
=> fix(workflow): Update Build Artifact to v4

src/types/types.rs, tests/test_factory.rs
The previous endpoint, `https://api-mainnet.helius-rpc.com/` does not exist.
=> fix: changed api mainnet endpoint

src/types/enhanced_websocket.rs
Hi there!
I realized that on the transactionSubscribe websocket we get the `slot` information. But it's currently not a field of the TransactionNotification struct, so it's not usable in Rust code. Did I miss something, or could this addition be considered?
=> Add slot to transaction notification

Cargo.toml
Patch curve25519-dalek with the same version solana sdk uses:
https://github.com/solana-labs/solana/blob/27eff8408b7223bb3c4ab70523f8a8dca3ca6645/Cargo.toml#L475-L563
=> Update reqwest back to v12. patch curve25519-dalek

src/types/enhanced_transaction_types.rs
Fixes
```
Failed to parse transactions for signatures, error: SerdeJson(Error("missing field `InstructionError`", ...))
```
Encountered when calling `helius::Helius.parse_transactions` ala:
```
match state.helius.parse_transactions(req).await {
Ok(transactions) => {
for transaction in transactions {
crate::enhanced_transactions::ingest_essentials(&state, transaction).await?;
}
}
```
=> Fix instruction error serialization 0.2.1

examples/send_smart_transaction_with_tip.rs, src/jito.rs, src/optimized_transaction.rs, src/types/types.rs
Closes #83 
Wraps into `Arc` variables that were referenced with lifetime in CreateSmartTransactionConfig
=> feat: Replace lifetimes with Arc for CreateSmartTransactionConfig

examples/send_smart_transaction_with_tip.rs, src/optimized_transaction.rs, src/types/types.rs
This PR allows users to cap the priority fees for a given smart transaction at a specific number and use that as the maximum possible value instead of using what is strictly returned by the Priority Fee API 
Consider the following scenarios where we cap priority fees at 10k:
- If the priority fee estimate based on the serialized transaction is 5k, then we'd use 5k
- If the priority fee estimate based on the serialized transaction is 10k, then we'd use 10k
- If the priority fee estimate based on the serialized transaction is 15k, then we'd use 10k
This also resolves #81
=> feat(optimized_transaction): Add Priority Fee Cap

examples/enhanced_websocket_accounts.rs, examples/enhanced_websocket_transactions.rs, src/client.rs, src/websocket.rs
This PR aims to implement better health checks for websockets by integrating better health connection monitoring via ping-pongs. Users can now configure the duration between ping messages and the duration to wait for a pong response before considering the connection dead using the new `new_with_ws_with_timeouts` method
Users can continue using `new_with_ws` without any hiccups, as this PR is designed to be backwards compatible with the default values
=> feat(ws): Better Health Checks

examples/async_config_based_creation.rs, src/config.rs, tests/test_config.rs
This PR aims to allow users to create `Helius` clients directly from `Config` instances, providing an alternative way for client initialization. Users can now create clients either through the traditional approach or through the following config-based methods added:
- `create_client()`: Creates a basic `Helius` client
- `create_client_with_async()`: Creates a client with async Solana support
- `create_client_with_ws()`: Creates a client with WebSocket support and configurable timeouts
- `create_full_client()`: Creates a fully-featured client
=> feat(client): Allow Config-based Client Creation

Cargo.toml
This PR aims to resolve #96 by fixing all dep-related issues. I've removed the patch for `curve25519-dalek` as it's no longer required, as well as updated all Solana-related deps to the latest version
=> fix(deps): Remove Patch, Fix Dep Conflicts

src/types/types.rs
This PR aims to resolve #100 by removing the incorrect renaming of `token_info`
=> fix(types): Incorrect Field Renaming

src/enhanced_transactions.rs, src/types/enhanced_transaction_types.rs, src/types/types.rs
Within the `Asset` type, there was an incorrect `#[serde(rename = "tokenSupply")]` for the `token_info` field. As is, it always returns `None` because there is no `tokenSupply` field in the response body.
=> fix(search_assets): Issue with field deserialization

examples/get_parsed_transaction_history.rs, examples/send_smart_transaction_with_seeds.rs, src/optimized_transaction.rs, tests/rpc/test_get_assets_by_authority.rs, tests/rpc/test_get_assets_by_creator.rs, tests/rpc/test_get_assets_by_group.rs, tests/rpc/test_get_assets_by_owner.rs, tests/rpc/test_search_assets.rs, tests/test_enhanced_transactions.rs
This PR aims to resolve #102 by refactoring `send_smart_transaction_with_seeds`. Previously, we erroneously assigned the signers to `Vec<Arc<dyn Signer>>`. This PR refactors the code to make it thread-safe, as well as implements a thread-safe version of `get_compute_units` (i.e., `get_compute_units_thread_safe`
This code also fixes broken tests and formatting
=> fix(optimized_transaction): Refactor `send_smart_transaction_with_seeds`

src/jito.rs, src/optimized_transaction.rs
As the title suggests, this PR aims to implement `send_smart_transaction_with_seeds_and_tip`. We also add `create_smart_transaction_with_seeds` to streamline thread-safe transaction creation with seeds instead of `Signers`
=> feat(txs): Implement `send_smart_transaction_with_seeds_and_tip`

src/optimized_transaction.rs
This is a quick PR to raise the priority fees for our smart transactions to `High`, rather than rely on the `recommended` value returned by our priority fee API
=> feat(optimized_transaction): Increase Priority Fees to High

README.md, examples/mint_cnft.rs, src/mint_api.rs, tests/test_mint_api.rs
This PR aims to tag `mint_compressed_nft` as deprecated, as we have deprecated the Mint API
=> feat(cNFT): Mark mint_compressed_nft as Deprecated

Cargo.toml
Unconditionally enabling `native-tls` forces it on for all users, making it impossible to build or run without `libssl` on Linux.
It's already enabled by the default features of this crate, so there's no need to force it on.
=> Remove forced `native-tls` features

src/types/types.rs, tests/rpc/test_get_asset.rs, tests/rpc/test_get_asset_batch.rs, tests/rpc/test_get_assets_by_authority.rs, tests/rpc/test_get_assets_by_creator.rs, tests/rpc/test_get_assets_by_group.rs, tests/rpc/test_get_assets_by_owner.rs, tests/rpc/test_search_assets.rs
This PR aims to resolve #114, where `Metadata` would have the wrong data structure for some assets, by adding in a new `Attributes` enum
=> fix(types): Add `Attributes` Enum

src/types/types.rs
When querying the account `9apnHjEQ8enLaPLxP7z9VQTphWE4nWqZcyHJYocQMpSE` via `searchAssets`, the asset `5gVSjqSbBhrCsUFz3pE6ZnrNiEyxMXzmN92XPTc4b9kS` is returned with a non-null `GroupDefintion` field which doesn't include an `asset_id` field. 
This leads to a failed deser of the `GroupDefintion` struct and the subsequent `Asset` and `AssetList` structs
Make the `asset_id` field in the `GroupDefintion` struct optional
=> fix: make asset_id field in GroupDefinition optional

Cargo.toml, src/lib.rs, src/staking.rs
This PR aims to add staking functionality via the following methods:
- `create_stake_transaction`
- `create_unstake_transaction`
- `create_withdraw_transaction`
- `get_stake_instructions`
- `get_unstake_instruction`
- `get_withdraw_instruction`
- `get_withdrawable_amount`
- `get_stake_accounts`
=> feat(staking): Add Staking Functionality

README.md, src/optimized_transaction.rs
This PR aims to update the documentation to showcase the new Sender methods, as well as note that Jito methods are now deprecated and will be removed in a future release
=> feat(docs): Update Documentation With Sender Methods
